spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pessoas
    username: pessoas
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

cadastro-unico:
  base-url: https://plataforma-cadastro-unico.betha.cloud
  token: seutokenaqui   # Bearer token gerado no Studio
  user-access: seuuseraccessaqui   # User-Access gerado no Studio

oauth2:
  token-info-url: https://plataforma-oauth.betha.cloud/auth/oauth2/tokeninfo

webhook:
  jwt-secret: suasecretkeyaqui   # Chave secreta para validar webhooks (≥ 32 caracteres)
  jwt-algorithm: HS256

logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8081